# Generated by Django 3.1.7 on 2021-02-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_title', models.CharField(max_length=250)),
                ('bookmark_link', models.URLField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
