# Generated by Django 3.1.7 on 2021-02-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20210222_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
