# Generated by Django 3.1.7 on 2021-02-26 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0005_auto_20210226_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='owner',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
