# Generated by Django 3.1.7 on 2021-02-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_bookmark_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='slug',
        ),
    ]
