# Generated by Django 3.1.7 on 2021-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0007_auto_20210226_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
