# Generated by Django 3.1.7 on 2021-02-28 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_demo_mode', '0002_auto_20210301_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demobookmark',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
