# Generated by Django 3.1.7 on 2021-03-01 00:24

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_demo_mode', '0003_auto_20210301_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demobookmark',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='demobookmark',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 0, 23, 47, 307149, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demobookmark',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
