# Generated by Django 3.1.7 on 2021-03-01 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_demo_mode', '0004_auto_20210301_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demobookmark',
            name='expiration_date',
        ),
    ]
