# Generated by Django 3.1.7 on 2021-03-01 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_demo_mode', '0005_remove_demobookmark_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demobookmark',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
