# Generated by Django 3.1.7 on 2021-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_demo_mode', '0006_auto_20210301_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demobookmark',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
